### ISSUE TITLE
Couldn’t find iOS Simulator

### ISSUE THREAD

**Issue by johnboyer** [lorenbrichter/SimFinger#14]
When I launch SimFinger, I see an alert “Couldn’t find iOS Simulator”

How can I resolve this issue?

System info:
I built the app using the supplied script with Xcode Version 3.2.4 for iOS 4.1.
System Version: Mac OS X 10.6.6 (10J567)
Kernel Version: Darwin 10.6.0

Regards,
John Boyer

**Comment by desolationrift** [comment]
I'm having the same problem and I have no clue what to do can someone help us.

**Comment by sefran** [comment]
For me, the same. I tried to change the path, but nothing.
Xcode 3.2.2, Simulator 3.1.3
Mac OS X 10.6.6

**Comment by andrewdever** [comment]
Any solution?

**Comment by enderchen** [comment]
I got the same error... so how to solve it?

**Comment by druidLike** [comment]
If you want to hack a temp. fix, I got landscape to work on 10.6.7 with the following hacks:
In FakeFingerAppDelegate.m in the method 'positionSimulatorWindow', I added the following -

Look for this code -
NSLog(@"Simulator current size: %d, %d", (int)size.width, (int)size.height);

```
        BOOL supportedSize = NO;
        BOOL iPadMode = NO;
        BOOL landscape = NO;
        int iPhoneWidth = 368;
        int iPhoneHeight = 716;
        int iPadWidth = 852;
        int iPadHeight = 1108;
```

Then add this after it -

iPhoneWidth = 386;
iPhoneHeight = 742;
size.width = 742;
size.height = 386;

One other change needed -

Change the app name to 'iPhone Simulator' instead of 'iOS Simulator' in the line
if([[application objectForKey:@"NSApplicationName"] isEqualToString:@"iOS Simulator"])

**Comment by lpotherat** [comment]
In fact, you have to put the localized name of the ios simulator program at this line.

In french it is : @"Simulateur iOS"

This name is the name displayed in the menu bar.

**Comment by johnboyer** [comment]
I’ve never heard a peep from the developer about this problem. I’m going to try this app instead:http://www.jaml.co.uk/simcap.html
